// Package lima implements the Backend contract via a Lima VM (vz on macOS,
// QEMU/KVM on Linux). The rendered template below is the CONTAINMENT SURFACE:
// exactly one writable mount (the project tree at /lever), all automatic
// guest→host port-forwarding suppressed (lima's default forwards every guest
// listener to host 127.0.0.1 — a jailed agent could squat host-loopback ports
// and impersonate local services), and lima's bundled containerd disabled
// (lever provisions rootless podman/docker itself, mirroring orbstack).
// Do not add mounts or forwards without a security review (zone Z1).
package lima

import (
	"bytes"
	"runtime"
	"text/template"
)

const templateText = `# Generated by lever — the lima jail containment surface. Do not edit.
vmType: {{.VMType}}
{{- if eq .VMType "vz"}}
mountType: virtiofs
{{- end}}
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
disk: {{.Disk}}
mounts:
  - location: {{printf "%q" .ProjectTree}}
    mountPoint: "/lever"
    writable: true
containerd:
  system: false
  user: false
portForwards:
  - guestIP: "0.0.0.0"
    # explicit: auto-inference only since lima 2.0 (4d04ff37)
    guestIPMustBeZero: true
    guestPortRange: [1, 65535]
    # proto defaults to "tcp" when omitted; lima's builtin fallback forward rule
    # is proto: "any" and forwards UDP guest listeners too, so an omitted proto
    # here would leave UDP auto-forwarding unsuppressed.
    proto: "any"
    ignore: true
  - guestIP: "127.0.0.1"
    guestPortRange: [1, 65535]
    proto: "any"
    ignore: true
`

var tpl = template.Must(template.New("lima").Parse(templateText))

// defaultDisk caps the Lima guest disk. Lima's own omitted-disk default is
// 100GiB (grow-only qcow2 on the host) — a silent host-wedge on smaller
// hosts. Applied only at VM creation; resizing an existing jail needs
// `limactl disk resize` or a recreate.
const defaultDisk = "24GiB"

// RenderTemplate renders the jail VM template for this host OS. disk is the
// guest disk size (e.g. "24GiB"); empty selects defaultDisk.
func RenderTemplate(projectTree, disk string) (string, error) {
	if disk == "" {
		disk = defaultDisk
	}
	vmType := "qemu"
	if runtime.GOOS == "darwin" {
		vmType = "vz"
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, struct{ VMType, ProjectTree, Disk string }{vmType, projectTree, disk}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
