// Package lima implements the Backend contract via a Lima VM (vz on macOS,
// QEMU/KVM on Linux). The rendered template below is the CONTAINMENT SURFACE:
// exactly one writable mount (the project tree at /lever), all automatic
// guest→host port-forwarding suppressed (lima's default forwards every guest
// listener to host 127.0.0.1 — a jailed agent could squat host-loopback ports
// and impersonate local services), and lima's bundled containerd disabled
// (lever provisions rootless podman/docker itself, mirroring orbstack).
// Do not add mounts or forwards without a security review (zone Z1).
package lima

import (
	"bytes"
	"runtime"
	"text/template"
)

const templateText = `# Generated by lever — the lima jail containment surface. Do not edit.
vmType: {{.VMType}}
{{- if eq .VMType "vz"}}
mountType: virtiofs
{{- end}}
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
disk: {{.Disk}}
{{- if .CPUs}}
cpus: {{.CPUs}}
{{- end}}
{{- if .Memory}}
memory: {{printf "%q" .Memory}}
{{- end}}
{{- if and .NestedVirt (eq .VMType "qemu")}}
vmOpts:
  qemu:
    cpuType:
      x86_64: host
      aarch64: host
{{- end}}
mounts:
  - location: {{printf "%q" .ProjectTree}}
    mountPoint: "/lever"
    writable: true
containerd:
  system: false
  user: false
portForwards:
  - guestIP: "0.0.0.0"
    # explicit: auto-inference only since lima 2.0 (4d04ff37)
    guestIPMustBeZero: true
    guestPortRange: [1, 65535]
    # proto defaults to "tcp" when omitted; lima's builtin fallback forward rule
    # is proto: "any" and forwards UDP guest listeners too, so an omitted proto
    # here would leave UDP auto-forwarding unsuppressed.
    proto: "any"
    ignore: true
  - guestIP: "127.0.0.1"
    guestPortRange: [1, 65535]
    proto: "any"
    ignore: true
`

var tpl = template.Must(template.New("lima").Parse(templateText))

// defaultDisk caps the Lima guest disk. Lima's own omitted-disk default is
// 100GiB (grow-only qcow2 on the host) — a silent host-wedge on smaller
// hosts. Applied only at VM creation; resizing an existing jail needs
// `limactl disk resize` or a recreate.
const defaultDisk = "24GiB"

// TemplateOpts are the per-instance values the template renders. Zero values
// select the defaults (defaultDisk; Lima's own CPU/memory defaults; no
// explicit cpuType).
type TemplateOpts struct {
	Disk       string
	CPUs       int
	Memory     string
	NestedVirt bool
}

// RenderTemplate renders the jail VM template for this host OS.
func RenderTemplate(projectTree string, o TemplateOpts) (string, error) {
	if o.Disk == "" {
		o.Disk = defaultDisk
	}
	vmType := "qemu"
	if runtime.GOOS == "darwin" {
		vmType = "vz"
	}
	data := struct {
		VMType, ProjectTree, Disk, Memory string
		CPUs                              int
		NestedVirt                        bool
	}{vmType, projectTree, o.Disk, o.Memory, o.CPUs, o.NestedVirt}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
