// Package lima implements the Backend contract via a Lima VM (vz on macOS,
// QEMU/KVM on Linux). The rendered template below is the CONTAINMENT SURFACE:
// exactly one writable mount (the project tree at /lever), all automatic
// guest→host port-forwarding suppressed (lima's default forwards every guest
// listener to host 127.0.0.1 — a jailed agent could squat host-loopback ports
// and impersonate local services), and lima's bundled containerd disabled
// (lever provisions rootless podman/docker itself, mirroring orbstack).
// Do not add mounts or forwards without a security review (zone Z1).
package lima

import (
	"bytes"
	"runtime"
	"text/template"
)

const templateText = `# Generated by lever — the lima jail containment surface. Do not edit.
vmType: {{.VMType}}
{{- if eq .VMType "vz"}}
mountType: virtiofs
{{- end}}
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
mounts:
  - location: {{printf "%q" .ProjectTree}}
    mountPoint: "/lever"
    writable: true
containerd:
  system: false
  user: false
portForwards:
  - guestIP: "0.0.0.0"
    # explicit: auto-inference only since lima 2.0 (4d04ff37)
    guestIPMustBeZero: true
    guestPortRange: [1, 65535]
    ignore: true
  - guestIP: "127.0.0.1"
    guestPortRange: [1, 65535]
    ignore: true
`

var tpl = template.Must(template.New("lima").Parse(templateText))

// RenderTemplate renders the jail VM template for this host OS.
func RenderTemplate(projectTree string) (string, error) {
	vmType := "qemu"
	if runtime.GOOS == "darwin" {
		vmType = "vz"
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, struct{ VMType, ProjectTree string }{vmType, projectTree}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
